services:
  - type: web
    name: employee-backend
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:AySUaQZIy6sSmk+T6RY7/++BdeDzaUmxf/c8vf2zmnU=
